### ISSUE TITLE
error

### ISSUE THREAD

**Issue by denzardten** [amiralirj/DarkAdvertizer#1]
from pyrogram.enums import ParseMode
ModuleNotFoundError: No module named 'pyrogram.enums'

**Comment by amiralirj** [comment]
Update your pyrogram Version by writing this code in consol : 
- pip install -U pyrogram

**Comment by amiralirj** [comment]
Solved ! So it must Be CLOSED

**Comment by amiralirj** [comment]
Solved ! So it must Be CLOSED
