### ISSUE TITLE
کار نکردن پنل مدیریت 

### ISSUE THREAD

**Issue by Sobhan2176** [amiralirj/DarkAdvertizer#10]
سلام توی پنل مدیریت ربات بعضی از دکمه هارو میزنم جواب نمیده آدرس فایل pathe رو هم درست زدم مشکل چیه

**Comment by amiralirj** [comment]
سلام وقتتون بخیر 

ارورتون برسی شد باید pyromod V1.5 باشه نباید ورژن 2 باشه !!
