### ISSUE TITLE
How to change language to english

### ISSUE THREAD

**Issue by motikolorado** [amiralirj/DarkAdvertizer#2]
Please how do we change the bot language to english?

**Comment by amiralirj** [comment]
you should translate ( CONFIG -->> BUTTONS.py & TEXTS.py  ) and change persian language to english , 
then you can run it in english 
u can contact me in telegram : @amiralirj_g 👍

**Comment by motikolorado** [comment]
Thats one hell of a job i did and ended up with a buggy bot that doesn't respond on lots of buttons

**Comment by motikolorado** [comment]
I mean I translated it to english and it wont respond.

**Comment by amiralirj** [comment]
message me in telegram i will fix it for you , 
However you should change  > plugins too for responding
