### ISSUE TITLE
Too many errors

### ISSUE THREAD

**Issue by motikolorado** [amiralirj/DarkAdvertizer#3]
I have done the translation to english. both buttons.py and text.py but too many errors popup when i run.
https://github.com/motikolorado/DarkAdvertizer.git
look at my translations. can you fix the text.py? i think i broke the code

**Comment by amiralirj** [comment]
did you change name of variables ?

**Comment by amiralirj** [comment]
you change text.py and buttons.py 
your problem is you have forgot to change pluggins 

for example : 
you should change 

`@Advertising.on_message(RJ.prv & RJ.regex('^ثبت اکانت 📥') , group=0)`

to

`@Advertising.on_message(RJ.prv & RJ.regex('^Account registration 📥') , group=0)`
