### ISSUE TITLE
ارور نداشتن سکه

### ISSUE THREAD

**Issue by Morteza820** [amiralirj/DarkAdvertizer#7]
سلام من خودمو به عنوان اونر تعریف کرده ام
ولی ربات برای خدمات بهم میگه سکی کافی نداری
دکمه انتقال سکه هم کار نمیکنه....

**Comment by amiralirj** [comment]
سلام وقتتون بخیر 
باید ایدی عددی خودتون رو به عنوان owner در فایل کانفیگ قرار بدید , همچنین ربات باید توی کانال خبر و کانال بنر ها ادمین باشد . 

ربات رو استارت کنید و به خودتون اشتراک بدید

**Comment by amiralirj** [comment]
سلام وقتتون بخیر 

ارورتون برسی شد باید pyromod V1.5 باشه نباید ورژن 2 باشه !!
