### ISSUE TITLE
بررسی ارور

### ISSUE THREAD

**Issue by Morteza820** [amiralirj/DarkAdvertizer#8]
![Screenshot (7)](https://github.com/amiralirj/DarkAdvertizer/assets/130897413/f8c6b4bd-6da2-47d6-8b9a-4f198ebada63)
لطفا ارور های منو بررسی کنید 
امکان انتقال سکه و سکه روزانه و... کلا امور سکه رو دسترسی ندارم.....

**Comment by amiralirj** [comment]
ادرس path رو توی فایل کانفیگ درست وارد کنید

**Comment by amiralirj** [comment]
سلام وقتتون بخیر 

ارورتون برسی شد باید pyromod V1.5 باشه نباید ورژن 2 باشه !!
